2023-01-13 13:39:17,852 INFO    MainThread:26171 [wandb_setup.py:_flush():71] setting env: {}
2023-01-13 13:39:17,852 INFO    MainThread:26171 [wandb_setup.py:_flush():71] setting login settings: {}
2023-01-13 13:39:17,853 INFO    MainThread:26171 [wandb_init.py:_log_setup():371] Logging user logs to /home/sohui/code/SSL_brats/code/wandb/run-20230113_133917-dz1kc4p5/logs/debug.log
2023-01-13 13:39:17,853 INFO    MainThread:26171 [wandb_init.py:_log_setup():372] Logging internal logs to /home/sohui/code/SSL_brats/code/wandb/run-20230113_133917-dz1kc4p5/logs/debug-internal.log
2023-01-13 13:39:17,853 INFO    MainThread:26171 [wandb_init.py:init():404] calling init triggers
2023-01-13 13:39:17,853 INFO    MainThread:26171 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2023-01-13 13:39:17,853 INFO    MainThread:26171 [wandb_init.py:init():460] starting backend
2023-01-13 13:39:17,854 INFO    MainThread:26171 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-01-13 13:39:18,050 INFO    MainThread:26171 [backend.py:ensure_launched():216] starting backend process...
2023-01-13 13:39:18,905 INFO    MainThread:26171 [backend.py:ensure_launched():221] started backend process with pid: 26491
2023-01-13 13:39:18,909 INFO    MainThread:26171 [wandb_init.py:init():469] backend started and connected
2023-01-13 13:39:18,923 INFO    MainThread:26171 [wandb_init.py:init():533] updated telemetry
2023-01-13 13:39:18,928 INFO    MainThread:26171 [wandb_init.py:init():563] communicating current version
2023-01-13 13:39:20,660 INFO    MainThread:26171 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.13.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-01-13 13:39:20,661 INFO    MainThread:26171 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2023-01-13 13:39:50,664 INFO    MainThread:26171 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2023-01-13 13:39:50,665 ERROR   MainThread:26171 [wandb_init.py:init():583] backend process timed out
2023-01-13 13:39:50,665 ERROR   MainThread:26171 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-01-13 13:40:01,994 INFO    MainThread:26171 [wandb_init.py:teardown():219] tearing down wandb.init
